name: Auto Green Commit 🟩

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 8 * * *'
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Update File
        run: |
          mkdir -p logs
          echo "🟩 Updated: $(date -u)" > logs/contribution.md
      
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🟩 Auto commit - $(date -u '+%Y-%m-%d')"
          commit_user_name: Galang0304
          commit_user_email: andiariegalang0@gmail.com
